

[[http]]
name = "example-http"
bind-addr = "127.0.0.1:9096"

  [[http.output]]
    name="local1"
    location = "http://127.0.0.1:8086/write"
    async = true
    # Follow configurations only works under async mode
    buffer-size-mb = 100
    max-batch-kb = 50
    initial-interval = "500ms"
    interval-multiplier = 3
    skip-delay-interval = "60s"

  [[http.output]]
    name="local2"
    location = "http://127.0.0.1:7086/write"
    async = false
    buffer-size-mb = 100
    max-batch-kb = 50
    initial-interval = "500ms"
    interval-multiplier = 3
    skip-delay-interval = "60s"

[[udp]]
name = "example-udp"
bind-addr = "127.0.0.1:9096"
read-buffer = 0 # default
output = [
    { name="local1", location="127.0.0.1:8089", mtu=512 },
    { name="local2", location="127.0.0.1:7089", mtu=1024 },
]
